language: node_js
node_js:
  - "0.12"

services:
  - mongodb

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -y
  - sudo apt-get install gdal-bin libgdal-dev

script:
  - npm test
